"""initial_schema

Revision ID: f860646fae05
Revises: 
Create Date: 2026-09-27 13:56:12.857203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f860646fae05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklists_org_job_type'), table_name='checklists')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_checklists_org_job_type'), 'checklists', ['organization_id', 'job_type'], unique=True)
    # ### end Alembic commands ###
